// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/darklightz-redesign/Current.tsx": () => import("../components/mockups/darklightz-redesign/Current.tsx"),
  "./components/mockups/darklightz-redesign/NewDirection.tsx": () => import("../components/mockups/darklightz-redesign/NewDirection.tsx")
};
